# Generated by Django 2.0.3 on 2018-06-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
